const {chromium}=require(process.env.INDOOR_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const [url,sample,output,music,image]=process.argv.slice(2);fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1366,height:900},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(30000);
 const ready=()=>page.waitForFunction(()=>!busy&&project()?.clips.length),clip=()=>page.evaluate(()=>structuredClone(projectClip()));
 try{
  await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Vídeos',exact:true}).click();await page.locator('#files').setInputFiles(sample);await ready();
  assert.equal(await page.locator('.track-header .clip-clock').count(),1);assert.equal(await page.locator('#clip-properties').isVisible(),false);assert.equal(await page.locator('#apply-selected').isVisible(),false);assert.match(await page.locator('#apply-all').textContent(),/Aplicar modelo/);
  const baseline=await clip(),span=baseline.out-baseline.in;
  await page.locator('.clip-clock').click();await page.locator('#clip-speed-percent').fill('50');assert.ok(Math.abs(Number(await page.locator('#clip-speed-duration').inputValue())-span/2)<.011);await page.screenshot({animations:'disabled',path:path.join(output,'velocidade-popup.png')});await page.locator('#clip-speed-dialog .clip-time-apply').click();assert.ok(Math.abs((await clip()).duration-span/2)<.034);
  await page.locator('.clip-clock').click();await page.locator('#clip-speed-duration').fill(String(span*2));assert.equal(Number(await page.locator('#clip-speed-percent').inputValue()),200);await page.locator('#clip-speed-dialog .clip-time-cancel').click();assert.ok(Math.abs((await clip()).duration-span/2)<.034);
  await page.locator('.layer-clip').dblclick();await page.locator('#clip-trim-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#clip-trim-selection').isVisible(),true);await page.locator('#clip-trim-in-range').focus();await page.keyboard.press('ArrowRight');assert.ok(Number(await page.locator('#clip-trim-in').inputValue())>0);await page.locator('#clip-trim-in').fill('1');await page.locator('#clip-trim-out').fill('4');await page.screenshot({animations:'disabled',path:path.join(output,'corte-duplo-clique.png')});await page.locator('#clip-trim-dialog .clip-time-apply').click();assert.equal((await clip()).in,1);assert.equal((await clip()).out,4);assert.ok(Math.abs((await clip()).duration-1.5)<.034);
  await page.locator('#montage-playhead').focus();await page.keyboard.press('Control+z');assert.equal((await clip()).in,baseline.in);await page.keyboard.press('Control+y');assert.equal((await clip()).in,1);
  await page.locator('.clip-clock').click();await page.locator('#clip-speed-percent').fill('500');await page.locator('#clip-speed-dialog .clip-time-apply').click();assert.equal(await page.locator('#clip-speed-dialog').isVisible(),true);assert.equal(await page.locator('#clip-speed-dialog .clip-time-error').isVisible(),true);await page.locator('#clip-speed-duration').fill('3');assert.equal(Number(await page.locator('#clip-speed-percent').inputValue()),100);await page.locator('#clip-speed-dialog .clip-time-apply').click();assert.equal((await clip()).duration,3);assert.match(await page.locator('#selection-count').textContent(),/3,00/);assert.equal(await page.locator('#number-pos-x').isVisible(),false);
  for(const [id,value] of [['clip-position-x','100'],['clip-position-y','50'],['clip-rotation','90'],['clip-scale-width','600']]){await page.locator('#'+id).fill(value);await page.locator('#'+id).press('Tab');}
  const settings=(await clip()).settings;assert.equal(settings.rotation,90);assert.ok(Math.abs(settings.x*settings.width-100)<.01);assert.ok(Math.abs(-settings.y*settings.height-50)<.01);assert.ok(Math.abs(await page.evaluate(()=>mediaGeometry(current()).drawW)-600)<=1);
  await page.screenshot({animations:'disabled',path:path.join(output,'propriedades-pixels-timeline.png')});
  await page.locator('.track-header [data-property=locked]').click();assert.equal(await page.locator('.clip-clock').isDisabled(),true);assert.equal(await page.locator('#clip-rotation').isDisabled(),true);await page.locator('.track-header [data-property=locked]').click();
  await page.locator('.layer-clip').dblclick();await page.locator('#clip-trim-in').fill('4.9');await page.locator('#clip-trim-out').fill('4');await page.locator('#clip-trim-dialog .clip-time-apply').click();assert.equal(await page.locator('#clip-trim-dialog .clip-time-error').isVisible(),true);await page.locator('#clip-trim-dialog .close').click();assert.equal((await clip()).in,1);
  await page.evaluate(()=>{info.nativePicker=false;window.showDirectoryPicker=undefined;});await page.locator('#open-export').click();await page.locator('#remote-folder-dialog').waitFor({state:'visible'});await page.locator('#use-browser-folder').click();await page.waitForFunction(()=>!busy&&plan?.files.length);
  assert.equal(await page.locator('#video-size').isVisible(),true);const download=page.waitForEvent('download',{timeout:90000});await page.locator('#confirm-export').click();const d=await download;await d.saveAs(path.join(output,'clip-dialogs-export.mp4'));await page.waitForFunction(()=>!busy&&$('export-result').textContent.includes('✓'),null,{timeout:90000});assert.doesNotMatch(await page.locator('#export-result').textContent(),/Falha/);
  await page.locator('[data-close="export-dialog"]').click();
  await page.evaluate(()=>{seekComposition(1);splitProjectClip();selectProjectClip(project().clips[0].id,false);});
  const other=await page.evaluate(()=>project().clips[1].id);await page.locator(`[data-clip="${other}"]`).dblclick();await page.locator('#clip-trim-dialog').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>projectClip().id),other);await page.keyboard.press('Escape');
  if(image){await page.locator('#files').setInputFiles(image);await page.waitForFunction(()=>!busy&&job.media.some(m=>m.kind==='image'));await page.evaluate(()=>addProjectClip(job.media.find(m=>m.kind==='image').id,null,0,{duration:3},true));await page.locator('.track-header .clip-clock').first().click();assert.equal(await page.locator('#clip-speed-percent-label').isVisible(),false);await page.locator('#clip-speed-duration').fill('2');await page.locator('#clip-speed-dialog .clip-time-apply').click();assert.equal((await clip()).duration,2);}
  if(music){await page.locator('#files').setInputFiles(music);await page.waitForFunction(()=>!busy&&job.media.some(m=>m.kind==='audio'));await page.evaluate(()=>{const m=job.media.find(m=>m.kind==='audio');const c=project().clips.find(c=>c.mediaId===m.id);if(c)selectProjectClip(c.id,false);else addProjectClip(m.id);});await page.locator('.audio-track .clip-clock').click();assert.equal(await page.locator('#clip-speed-percent-label').isVisible(),true);await page.locator('#clip-speed-percent').fill('50');await page.locator('#clip-speed-dialog .clip-time-apply').click();assert.equal(await page.evaluate(()=>projectMedia().kind),'audio');}
  assert.deepEqual(errors,[]);console.log(JSON.stringify({clock:true,inversePercentageAndDuration:true,cancel:true,doubleClickOnTimeline:true,cutKeepsSpeed:true,undoRedo:true,limitsAndLocks:true,cartesianPixelsAndScale:true,realExport:true,nonselectedDoubleClick:true,imageDuration:!!image,audioSpeed:!!music,errors}));
 }catch(e){console.error(e);await page.screenshot({animations:'disabled',path:path.join(output,'error.png')});console.error(JSON.stringify({errors,state:await page.evaluate(()=>({busy,toast:$('toast').textContent,dialogs:[...document.querySelectorAll('dialog[open]')].map(d=>d.id)})).catch(()=>null)}));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
