const {chromium}=require(process.env.INDOOR_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const [url,video,image,output]=process.argv.slice(2);fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>!busy&&project()),pixel=async(x,y)=>page.evaluate(([x,y])=>Array.from($('live-preview').getContext('2d').getImageData(x,y,1,1).data),[x,y]);
 try{
  await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Vídeos',exact:true}).click();await page.locator('#files').setInputFiles(video);await ready();await page.waitForFunction(()=>project()?.clips.length===1);
  assert.equal(await page.locator("#editor .logo-settings").isVisible(),false);await page.waitForFunction(()=>{const p=document.getElementById("live-preview").getContext("2d").getImageData(10,10,1,1).data;return p[0]+p[1]+p[2]>0;});const before=await pixel(10,10);
  await page.locator('#files').setInputFiles(image);await ready();assert.equal(await page.locator('.library-card').count(),2);assert.equal(await page.locator('.layer-clip').count(),1);
  await page.mouse.move(900,450);await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().width<100);await page.locator('.library-card').last().dragTo(page.locator('.new-track-drop'),{targetPosition:{x:4,y:20}});await page.waitForFunction(()=>project()?.clips.length===2);await ready();
  const id=await page.evaluate(()=>projectClip().id);assert.equal(await page.evaluate(()=>projectMedia().role),'media');assert.deepEqual(await page.locator('.track-header>strong').allTextContents(),['Vídeo 02','Vídeo 01']);assert.equal(await page.locator('#zoom').getAttribute('aria-label'),'Escala');
  await page.evaluate(()=>change({zoom:.2,x:.2,y:-.2}));await ready();await page.waitForFunction(()=>{const p=$('live-preview').getContext('2d').getImageData(896,216,1,1).data;return p[0]>240&&p[1]>240&&p[2]>240;});assert.deepEqual(await pixel(10,10),before);assert.equal(await page.locator('#media-transform-box').isVisible(),true);
  await page.evaluate(()=>change({mode:'background',color:'#0000ff'}));await ready();await page.waitForFunction(()=>$('live-preview').getContext('2d').getImageData(10,10,1,1).data[2]>240);await page.evaluate(()=>change({mode:'contain'}));await ready();
  await page.locator('#save-composition').click();await ready();const jobId=await page.evaluate(()=>job.id);await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'Edições recentes',exact:true}).click();await page.locator(`.recent-card[data-job-id="${jobId}"]`).click();await ready();await page.evaluate(id=>selectProjectClip(id),id);assert.equal(await page.locator('#editor .logo-settings').isVisible(),false);assert.equal(await page.evaluate(()=>projectClip().settings.zoom),.2);await page.waitForFunction(()=>{const p=$('live-preview').getContext('2d').getImageData(896,216,1,1).data;return p[0]>240&&p[1]>240&&p[2]>240;});assert.deepEqual(await pixel(10,10),before);
  await page.screenshot({path:path.join(output,'library-image-overlay.png')});
  await page.evaluate(()=>info.nativePicker=false);await page.locator('#open-export').click();await page.locator('#remote-path').fill(output);await page.locator('#use-remote-folder').click();await page.locator('#export-dialog').waitFor({state:'visible'});await page.waitForFunction(()=>!busy&&plan?.files.length===1);await page.locator('#export-name').fill('VT - Library overlay');await page.waitForFunction(()=>plan?.files[0]?.name.includes('Library overlay'));const exportedName=await page.evaluate(()=>plan.files[0].name);await page.locator('#confirm-export').click();await page.waitForFunction(()=>!busy&&$('export-result').textContent.includes('✓'),null,{timeout:90000});assert.ok(fs.existsSync(path.join(output,exportedName)));
  await page.locator('[data-close="export-dialog"]').click();await page.getByRole('button',{name:'Imagens',exact:true}).click();await page.locator('#files').setInputFiles(image);await page.waitForFunction(()=>!busy&&current()?.kind==='image');assert.equal(await page.locator('#editor .logo-settings').isVisible(),true);assert.deepEqual(errors,[]);console.log(JSON.stringify({logoSectionRemoved:true,libraryDrag:true,transparentPreview:true,explicitBackground:true,persistence:true,mp4:true,imageEditorPreserved:true,errors}));
 }catch(e){await page.screenshot({path:path.join(output,'overlay-error.png')});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});