const {chromium}=require(process.env.INDOOR_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');const [url,video]=process.argv.slice(2);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{await page.emulateMedia({reducedMotion:'reduce'});await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Vídeos',exact:true}).click();await page.locator('#files').setInputFiles(video);await page.waitForFunction(()=>!busy&&project()?.clips.length);
  await page.locator('#clip-proportion-lock').click();const width=Number(await page.locator('#clip-scale-width').inputValue());await page.locator('#clip-scale-width').fill(String(width/2));await page.locator('#clip-scale-width').press('Tab');const before=await page.evaluate(()=>structuredClone(projectClip().settings));
  const handle=await page.locator('.media-transform-handle.e').boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2+30,handle.y+handle.height/2,{steps:6});await page.mouse.up();const after=await page.evaluate(()=>projectClip().settings);assert(after.scaleX>before.scaleX);assert.equal(after.scaleY,before.scaleY);
  await page.locator('#montage-playhead').focus();await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>projectClip().settings.scaleX),before.scaleX);
  await page.locator('#clip-proportion-lock').click();assert.equal(await page.evaluate(()=>projectClip().settings.scaleX),1);assert.equal(await page.evaluate(()=>projectClip().settings.scaleY),1);
  await page.locator('#clip-proportion-lock').click();await page.locator('#clip-scale-height').fill(String(Number(await page.locator('#clip-scale-height').inputValue())/2));await page.locator('#clip-scale-height').press('Tab');assert.equal(await page.evaluate(()=>projectClip().settings.scaleX),1);assert.equal(await page.evaluate(()=>projectClip().settings.scaleY),.5);
  await page.locator('#montage-playhead').focus();await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>projectClip().settings.scaleY),1);assert.equal(await page.locator('#clip-proportion-lock').getAttribute('aria-pressed'),'true');
  for(const [input,expected] of [[-450,-90],[3600,0],[-3600,0]]){await page.locator('#clip-rotation').fill(String(input));await page.locator('#clip-rotation').press('Tab');assert.equal(Number(await page.locator('#clip-rotation').inputValue())||0,expected);}
  await page.locator('#clip-rotation').fill('-90');await page.locator('#clip-rotation').press('Tab');await page.evaluate(async()=>await save());assert.equal(await page.evaluate(()=>projectClip().settings.rotation),-90);assert.deepEqual(errors,[]);console.log(JSON.stringify({independentHandleDrag:true,undo:true,relink:true,heightOnly:true,home:true,signedRotationAndFullTurns:true,persistedNegativeAngle:true,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
